DROP TABLE IF EXISTS spawnlist;

DROP TABLE IF EXISTS ai_params;
DROP TABLE IF EXISTS droplist;
DROP TABLE IF EXISTS minions;
DROP TABLE IF EXISTS npc;
DROP TABLE IF EXISTS npcskills;
DROP TABLE IF EXISTS skill_learn;
DROP TABLE IF EXISTS spawnlist;